attempt to create /etc/xml if it does not exist so `rm -rf /etc/xml && build-docbook-catalog` works

diff --git a/build-docbook-catalog b/build-docbook-catalog
--- a/build-docbook-catalog
+++ b/build-docbook-catalog
@@ -9,8 +9,9 @@
 # written by Aron Griffis
 #
 
-ROOTCATALOG=/etc/xml/catalog
-CATALOG=/etc/xml/docbook
+ROOTCONFDIR=/etc/xml
+ROOTCATALOG=${ROOTCONFDIR}/catalog
+CATALOG=${ROOTCONFDIR}/docbook
 DOCBOOKDIR=/usr/share/sgml/docbook
 DTDS=
 LATEST_DTD=
@@ -112,6 +113,10 @@ set_dtds() {
 # create the catalogs root and docbook specific
 #
 create_catalogs() {
+	if [[ ! -d ${ROOTCONFDIR} ]] ; then
+		mkdir -p "${ROOTCONFDIR}" || error "could not create ${ROOTCONFDIR}"
+	fi
+
 	if [[ ! -r ${ROOTCATALOG} ]] ; then
 		echo "Creating XML Catalog root ${ROOTCATALOG}"
 		xmlcatalog --noout --create ${ROOTCATALOG}
